"""update

Revision ID: a04c696b19a2
Revises: c723fcf829c8
Create Date: 2025-11-06 09:47:56.179848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04c696b19a2'
down_revision: Union[str, None] = 'c723fcf829c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_act_numbers_company_deleted', table_name='act_numbers')
    op.create_index(op.f('ix_act_numbers_id'), 'act_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_appeals_id'), 'appeals', ['id'], unique=False)
    op.create_index(op.f('ix_base_tariff_plans_id'), 'base_tariff_plans', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_reports_id'), 'calendar_reports', ['id'], unique=False)
    op.drop_index('idx_cities_company_deleted_name', table_name='cities')
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.drop_index('idx_companies_verification_date_block', table_name='companies')
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_company_activities_id'), 'company_activities', ['id'], unique=False)
    op.create_index(op.f('ix_company_calendar_day_info_id'), 'company_calendar_day_info', ['id'], unique=False)
    op.create_index(op.f('ix_company_params_id'), 'company_params', ['id'], unique=False)
    op.create_index(op.f('ix_company_si_types_id'), 'company_si_types', ['id'], unique=False)
    op.add_column('company_tariff_history', sa.Column('base_tariff_id', sa.Integer(), nullable=True))
    op.add_column('company_tariff_history', sa.Column('title', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_company_tariff_history_base_tariff_id'), 'company_tariff_history', ['base_tariff_id'], unique=False)
    op.create_index(op.f('ix_company_tariff_history_id'), 'company_tariff_history', ['id'], unique=False)
    op.create_foreign_key(None, 'company_tariff_history', 'base_tariff_plans', ['base_tariff_id'], ['id'], ondelete='SET NULL')
    op.add_column('company_tariff_state', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('company_tariff_state', sa.Column('base_tariff_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_company_tariff_state_base_tariff_id'), 'company_tariff_state', ['base_tariff_id'], unique=False)
    op.create_index(op.f('ix_company_tariff_state_id'), 'company_tariff_state', ['id'], unique=False)
    op.create_foreign_key(None, 'company_tariff_state', 'base_tariff_plans', ['base_tariff_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_counter_assignments_id'), 'counter_assignments', ['id'], unique=False)
    op.drop_index('idx_employees_default_verifier_status', table_name='employees', postgresql_where='(is_active IS TRUE)')
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.drop_index('idx_employees_companies_company_id', table_name='employees_companies')
    op.drop_index('idx_employees_companies_employee_id', table_name='employees_companies')
    op.create_index(op.f('ix_equipment_info_id'), 'equipment_info', ['id'], unique=False)
    op.create_index(op.f('ix_equipments_id'), 'equipments', ['id'], unique=False)
    op.drop_index('idx_equipments_verifiers_verifier_id', table_name='equipments_verifiers')
    op.drop_index('idx_locations_company_deleted', table_name='locations')
    op.drop_index('idx_locations_company_id', table_name='locations')
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_methods_id'), 'methods', ['id'], unique=False)
    op.create_index(op.f('ix_metrologs_info_id'), 'metrologs_info', ['id'], unique=False)
    op.drop_index('idx_orders_company_id', table_name='orders')
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.drop_index('idx_reasons_company_isdeleted_name', table_name='reasons')
    op.drop_index('idx_reasons_company_type_isdeleted', table_name='reasons')
    op.create_index(op.f('ix_reasons_id'), 'reasons', ['id'], unique=False)
    op.drop_index('idx_registry_numbers_company_isdeleted', table_name='registry_numbers')
    op.drop_index('idx_registry_numbers_company_isdeleted_regnum', table_name='registry_numbers')
    op.create_index(op.f('ix_registry_numbers_id'), 'registry_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_route_additions_id'), 'route_additions', ['id'], unique=False)
    op.create_index(op.f('ix_route_statistic_id'), 'route_statistic', ['id'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.drop_index('idx_act_series_company_deleted_name', table_name='series')
    op.create_index(op.f('ix_series_id'), 'series', ['id'], unique=False)
    op.create_index(op.f('ix_si_modifications_id'), 'si_modifications', ['id'], unique=False)
    op.drop_index('idx_teams_company_isdeleted', table_name='teams')
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.drop_index('idx_verif_act_number_id', table_name='verification_entries')
    op.drop_index('idx_verif_company_date_id', table_name='verification_entries')
    op.drop_index('idx_verif_company_date_series_employee', table_name='verification_entries')
    op.drop_index('idx_verif_company_employee_date', table_name='verification_entries')
    op.drop_index('idx_verif_company_factory_date', table_name='verification_entries')
    op.drop_index('idx_verif_company_series_employee', table_name='verification_entries')
    op.drop_index('idx_verification_entries_company_employee', table_name='verification_entries')
    op.create_index(op.f('ix_verification_entries_id'), 'verification_entries', ['id'], unique=False)
    op.create_index(op.f('ix_verification_entry_photos_id'), 'verification_entry_photos', ['id'], unique=False)
    op.drop_index('idx_verification_logs_verifier_date', table_name='verification_logs')
    op.create_index(op.f('ix_verification_logs_id'), 'verification_logs', ['id'], unique=False)
    op.create_index(op.f('ix_verification_reports_id'), 'verification_reports', ['id'], unique=False)
    op.alter_column('verifier_equipment_history', 'action',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('accepted', 'declined', name='verifier_equipment_action_enum'),
               existing_nullable=False,
               postgresql_using='action::verifier_equipment_action_enum')
    op.create_index(op.f('ix_verifier_equipment_history_id'), 'verifier_equipment_history', ['id'], unique=False)
    op.drop_index('idx_verifiers_company_id', table_name='verifiers')
    op.drop_index('idx_verifiers_company_isdeleted', table_name='verifiers')
    op.drop_index('idx_verifiers_company_team_isdeleted', table_name='verifiers')
    op.create_index(op.f('ix_verifiers_id'), 'verifiers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifiers_id'), table_name='verifiers')
    op.create_index('idx_verifiers_company_team_isdeleted', 'verifiers', ['company_id', 'team_id', 'is_deleted'], unique=False)
    op.create_index('idx_verifiers_company_isdeleted', 'verifiers', ['company_id', 'is_deleted'], unique=False)
    op.create_index('idx_verifiers_company_id', 'verifiers', ['company_id', 'id'], unique=False)
    op.drop_index(op.f('ix_verifier_equipment_history_id'), table_name='verifier_equipment_history')
    op.alter_column('verifier_equipment_history', 'action',
               existing_type=sa.Enum('accepted', 'declined', name='verifier_equipment_action_enum'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False,
               postgresql_using='action::verifier_equipment_action_enum')
    op.drop_index(op.f('ix_verification_reports_id'), table_name='verification_reports')
    op.drop_index(op.f('ix_verification_logs_id'), table_name='verification_logs')
    op.create_index('idx_verification_logs_verifier_date', 'verification_logs', ['verifier_id', 'verification_date'], unique=False)
    op.drop_index(op.f('ix_verification_entry_photos_id'), table_name='verification_entry_photos')
    op.drop_index(op.f('ix_verification_entries_id'), table_name='verification_entries')
    op.create_index('idx_verification_entries_company_employee', 'verification_entries', ['company_id', 'employee_id'], unique=False)
    op.create_index('idx_verif_company_series_employee', 'verification_entries', ['company_id', 'series_id', 'employee_id'], unique=False)
    op.create_index('idx_verif_company_factory_date', 'verification_entries', ['company_id', sa.text('lower(factory_number::text)'), 'verification_date'], unique=False)
    op.create_index('idx_verif_company_employee_date', 'verification_entries', ['company_id', 'employee_id', sa.text('verification_date DESC')], unique=False)
    op.create_index('idx_verif_company_date_series_employee', 'verification_entries', ['company_id', sa.text('verification_date DESC'), 'series_id', 'employee_id'], unique=False)
    op.create_index('idx_verif_company_date_id', 'verification_entries', ['company_id', sa.text('verification_date DESC'), sa.text('id DESC')], unique=False)
    op.create_index('idx_verif_act_number_id', 'verification_entries', ['act_number_id'], unique=False)
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.create_index('idx_teams_company_isdeleted', 'teams', ['company_id', 'is_deleted'], unique=False)
    op.drop_index(op.f('ix_si_modifications_id'), table_name='si_modifications')
    op.drop_index(op.f('ix_series_id'), table_name='series')
    op.create_index('idx_act_series_company_deleted_name', 'series', ['company_id', 'is_deleted', 'name'], unique=False)
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_index(op.f('ix_route_statistic_id'), table_name='route_statistic')
    op.drop_index(op.f('ix_route_additions_id'), table_name='route_additions')
    op.drop_index(op.f('ix_registry_numbers_id'), table_name='registry_numbers')
    op.create_index('idx_registry_numbers_company_isdeleted_regnum', 'registry_numbers', ['company_id', 'is_deleted', 'registry_number'], unique=False)
    op.create_index('idx_registry_numbers_company_isdeleted', 'registry_numbers', ['company_id', 'is_deleted'], unique=False)
    op.drop_index(op.f('ix_reasons_id'), table_name='reasons')
    op.create_index('idx_reasons_company_type_isdeleted', 'reasons', ['company_id', 'type', 'is_deleted'], unique=False)
    op.create_index('idx_reasons_company_isdeleted_name', 'reasons', ['company_id', 'is_deleted', 'name'], unique=False)
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.create_index('idx_orders_company_id', 'orders', ['company_id', 'id'], unique=False)
    op.drop_index(op.f('ix_metrologs_info_id'), table_name='metrologs_info')
    op.drop_index(op.f('ix_methods_id'), table_name='methods')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.create_index('idx_locations_company_id', 'locations', ['company_id', 'id'], unique=False)
    op.create_index('idx_locations_company_deleted', 'locations', ['company_id', 'is_deleted'], unique=False)
    op.create_index('idx_equipments_verifiers_verifier_id', 'equipments_verifiers', ['verifier_id', 'equipment_id'], unique=False)
    op.drop_index(op.f('ix_equipments_id'), table_name='equipments')
    op.drop_index(op.f('ix_equipment_info_id'), table_name='equipment_info')
    op.create_index('idx_employees_companies_employee_id', 'employees_companies', ['employee_id'], unique=False)
    op.create_index('idx_employees_companies_company_id', 'employees_companies', ['company_id'], unique=False)
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.create_index('idx_employees_default_verifier_status', 'employees', ['default_verifier_id', 'status'], unique=False, postgresql_where='(is_active IS TRUE)')
    op.drop_index(op.f('ix_counter_assignments_id'), table_name='counter_assignments')
    op.drop_constraint(None, 'company_tariff_state', type_='foreignkey')
    op.drop_index(op.f('ix_company_tariff_state_id'), table_name='company_tariff_state')
    op.drop_index(op.f('ix_company_tariff_state_base_tariff_id'), table_name='company_tariff_state')
    op.drop_column('company_tariff_state', 'base_tariff_id')
    op.drop_column('company_tariff_state', 'title')
    op.drop_constraint(None, 'company_tariff_history', type_='foreignkey')
    op.drop_index(op.f('ix_company_tariff_history_id'), table_name='company_tariff_history')
    op.drop_index(op.f('ix_company_tariff_history_base_tariff_id'), table_name='company_tariff_history')
    op.drop_column('company_tariff_history', 'title')
    op.drop_column('company_tariff_history', 'base_tariff_id')
    op.drop_index(op.f('ix_company_si_types_id'), table_name='company_si_types')
    op.drop_index(op.f('ix_company_params_id'), table_name='company_params')
    op.drop_index(op.f('ix_company_calendar_day_info_id'), table_name='company_calendar_day_info')
    op.drop_index(op.f('ix_company_activities_id'), table_name='company_activities')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.create_index('idx_companies_verification_date_block', 'companies', ['verification_date_block'], unique=False)
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.create_index('idx_cities_company_deleted_name', 'cities', ['company_id', 'is_deleted', 'name'], unique=False)
    op.drop_index(op.f('ix_calendar_reports_id'), table_name='calendar_reports')
    op.drop_index(op.f('ix_base_tariff_plans_id'), table_name='base_tariff_plans')
    op.drop_index(op.f('ix_appeals_id'), table_name='appeals')
    op.drop_index(op.f('ix_act_numbers_id'), table_name='act_numbers')
    op.create_index('idx_act_numbers_company_deleted', 'act_numbers', ['company_id', 'is_deleted'], unique=False)
    # ### end Alembic commands ###
